spring:
  datasource:
    url: ${PG_DB_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

app:
  jwtSecret: oMRduQDUnscUHpOkE6hwt8V5JWgGVHH9CIQqrRfSREXz5AnN+ZZkrsayGOBGgky6
  jwtExpirationInMs: 36000000
  refreshExpirationInMs: 259200000

server:
  port: 8080